---
title: "Analysis of domains in alternative TF isoforms"
author: "Sviatoslav Sidorov"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    collapsed: no
    fig_align: center
    fig_caption: yes
    highlight: haddock
    keep_md: yes
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r, include=T}
stringsAsFactors = F
library(tidyverse)
library(scales)
library(kableExtra)
library(biomaRt)
library(seqinr)
library(yaml)
library(data.tree)
library(XLConnect)
library(msa)
```

## Print package versions

Print versions of the loaded libraries:

```{r, include=T}
packageVersion("tidyverse")
packageVersion("scales")
packageVersion("kableExtra")
packageVersion("biomaRt")
packageVersion("seqinr")
packageVersion("yaml")
packageVersion("data.tree")
packageVersion("XLConnect")
packageVersion("msa")
```

## Read input and organise output

Read args and create output paths:

```{r, include=T}
args = commandArgs()

humantfs_name = args[9]

#output.name = paste0(sub('\\.tsv', '', input.name), "_processed.tsv")

tables_dir = "tables"
dir.create(file.path(".", tables_dir))

figure_panels_dir = "figure_panels"
dir.create(file.path(".", figure_panels_dir))
```

## Retrieve and count all human TFs from the HumanTFs database

First, retrieve all transcription factors from the [Human Transcription Factors](http://humantfs.ccbr.utoronto.ca/index.php) database ([Lambert et al., 2018](https://www.sciencedirect.com/science/article/pii/S0092867418301065?via%3Dihub)):

```{r, include=T}
print(humantfs_name)
# humantfs_name
# humantfs = as_tibble(read.csv(file = "data/humantfs1.01/DatabaseExtract_v_1.01.csv", header = T, row.names = 1))
humantfs = as_tibble(read.csv(file = humantfs_name, header = T, row.names = 1))
```
